apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: suse-webui-demo-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - hosts:
        - rancher.kodyrepo.online
      secretName: rancher
  rules:
    - host: rancher.kodyrepo.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: suse-webui-demo
                port:
                  number: 443
